# Generated by Django 4.2.6 on 2023-10-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_projecttasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTasks',
        ),
    ]
