# Generated by Django 4.2.6 on 2023-11-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_projecttasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='Описание проекта...'),
        ),
        migrations.AddField(
            model_name='project',
            name='taks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='content',
            field=models.TextField(default='Описание задачи...'),
        ),
    ]
