# Generated by Django 4.2.6 on 2023-11-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_tasks_project_project_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.project'),
        ),
        migrations.DeleteModel(
            name='Project_tasks',
        ),
    ]
